Controllers/ContesterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MakingFuss.Data;
using System.Web;

using MakingFuss.Services;

namespace MakingFuss.Controllers
{
    [Route("[controller]/[action]")]
    [ApiController]
    public class ContesterController : Controller
    {
        private static ContesterService ContesterService;
        private static SlackService SlackService;

        public ContesterController(ContesterService contesterService, SlackService slackService)
        {
            ContesterService = contesterService;
            SlackService = slackService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var allContesters = await ContesterService.GetAllContestersOrderedByRatio();
            return View(allContesters);

        }

        [HttpPost]
        public async Task<IActionResult> PayloadFromSlack([FromForm] string payload)
        {
            var decodedPayload = HttpUtility.UrlDecode(payload);
            Payload payloadObject = Newtonsoft.Json.JsonConvert.DeserializeObject<Payload>(decodedPayload);
            var capitalizedName = UppercaseName(payloadObject.User.Name);
            string message = "";
            if (payloadObject.Actions.FirstOrDefault().Value == "click_me_go") // Message according to which button the user pressed in Slack
            {
                message = $"➕ {capitalizedName} er med!";
            }
            else
            {
                message = $"➖ {capitalizedName} kan ikke nå!";
            }
            await SlackService.LogToSlack(message);
            return Ok();
        }

        [HttpPost] // Handles Slack-interaction. "/fuss" and "/fuss score"
        public async Task<IActionResult> SlashProposeGame(SlashPayload payload)
        {
            if (payload.text == "score") // TODO: Switch statement instead
            {
                var leaders = (await ContesterService.GetAllContestersOrderedByRatio()).Take(10);
                await SlackService.PostTop10Scoreboard(leaders);
            }
            else if (payload.text == "enroll")
            {

                var contester = new Contester();
                var slackUserId = payload.user_id;

                if (await ContesterService.IsEnrolledBySlackId(slackUserId))
                {
                    await SlackService.LogToSlack($"Cannot enroll new contester. <@{slackUserId}> is already enrolled!");
                }
                else
                {
                    SlackUserProfile userProfile;
                    try
                    {
                        userProfile = await SlackService.GetUserProfile(slackUserId);
                    }
                    catch (Exception e)
                    {
                        await SlackService.LogToSlack(e.Message);
                        throw e;
                    }

                    contester.Name = userProfile.RealNameNormalized;
                    contester.SlackUserId = slackUserId;

                    await ContesterService.AddNew(contester);
                    await SlackService.LogNewUser(contester);
                }


            }
            else if (payload.text == "reveal_id")
            {

                await SlackService.LogToSlack($"<@{payload.user_id}> user id is *{payload.user_id}*");

            }
            else if (payload.text == "win")
            {
                await RegisterWin(payload.user_id);
            }
            else if (payload.text == "loss")
            {
                await RegisterLoss(payload.user_id);
            }
            else
            {
                // TODO: get Contester by slack handle
                Contester user;
                try
                {
                    user = await ContesterService.getUserBySlackId(payload.user_id);
                }
                catch (InvalidOperationException e)
                {
                    await SlackService.LogToSlack($"Can't find the user profile for id {payload.user_id}. Have you done `/fuss enroll`?");
                    throw e;
                }
                await SlackService.ProposeNewgame(user);
            }
            return Ok();
        }

        [HttpGet] // Get the create-page view (new user/contester)
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost] // Create a new contester
        public async Task<IActionResult> Create([Bind("Name", "SlackUserId")] Contester contester)
        {


            await ContesterService.AddNew(contester);
            await SlackService.LogNewUser(contester);

            return RedirectToAction("Index");
        }

        [HttpGet] // Submit a win // Fordi ActionLink er en GET.. (?)
        public async Task<IActionResult> AddWin(string SlackUserId)
        {
            await RegisterWin(SlackUserId);

            return RedirectToAction("Index");
        }

        [HttpGet] // Submit a loss
        public async Task<IActionResult> AddLoss(string SlackUserId)
        {
            await RegisterLoss(SlackUserId);
            return RedirectToAction("Index");
        }


        [HttpGet]
        public async Task<IActionResult> ProposeGame()
        {
            await SlackService.ProposeNewgame(null);
            return RedirectToAction("Index");
        }




        ///////////////////// HELPER FUNCTIONS //////////////////////////////////////

        private async Task RegisterWin(string contesterId)
        {
            var leaderPre = await ContesterService.GetLeader();
            var contester = await ContesterService.getUserBySlackId(contesterId);

            await ContesterService.RegisterWin(contester);
            await SlackService.LogToSlack($"{contester.Name} submitted a win.");

            var leaderPost = await ContesterService.GetLeader();

            if (leaderPre.ContesterId != leaderPost.ContesterId)
            {
                await SlackService.LogToSlack($":crown: :crown: :crown: <@{leaderPost.SlackUserId}> is now the new leader :crown: :crown: :crown:");
            }
        }
        private async Task RegisterLoss(string contesterId)
        {
            var leaderPre = await ContesterService.GetLeader();

            var contester = await ContesterService.getUserBySlackId(contesterId);
            await ContesterService.RegisterLoss(contester);

            await SlackService.LogToSlack($"{contester.Name} submitted a loss.");

            var leaderPost = await ContesterService.GetLeader();

            if (leaderPre.ContesterId != leaderPost.ContesterId)
            {
                await SlackService.LogToSlack($":crown: :crown: :crown: <@{leaderPost.SlackUserId}> is now the new leader :crown: :crown: :crown:");
            }
        }



        [NonAction]
        public string UppercaseName(string userName)
        {
            var nameCapitalized = userName[0].ToString().ToUpper() + userName.Substring(1);
            return nameCapitalized;
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Making Waves</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
    <link href="@Url.Content("~/css/site.css")" rel="stylesheet" type="text/css" />
    @RenderSection("Styles", false)
</head>
<body>
<div class="box">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Contester" asp-action="Index">MakingFuss</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contester" asp-action="Index">Leaderboard</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
           <b></b></div>

    <footer class="footer text-muted">
        <div class="container">
            &copy; 2019 - MW
        </div>
    </footer>

        @* URL "animation" *@
    <script>
        var f = ['🕺', '🌑', '_', '_', '_', '_', '_', '_', '_', '_', '_', '_', '_', '_', '_', '🚶'];
        var moon = ['🌒','🌓','🌔','🌕','🌖','🌗','🌘','🌑'];
          async function sleep (time) {
            return new Promise((resolve) => setTimeout(resolve, time));
        }
        async function loop() {
            var counter = 1;
            var countForward = true;
            var moonCounter = 0;
            while(true){
                f[counter%f.length] = '_';
                if(countForward){
                    counter += 1;
                } else{
                    counter -= 1;
                }
                if(counter == f.length){ // if at end
                    countForward = false;
                    f[f.length-1] = '🏃';
                    f[f.length-2] = moon[moonCounter];
                    location.hash = f.join('');
                    await sleep(300);
                } else if (counter == 1){ // if back at start
                    countForward = true;
                    f[0] = '💃';
                    f[counter%f.length] = moon[moonCounter];
                    location.hash = f.join('');
                    await sleep(300);
                } else if(counter > 1 && counter < f.length-2){ // inbetween
                    f[0] = '🕺';
                    f[f.length-1] = '🚶';
                    f[counter] = moon[moonCounter];
                    moonCounter += 1;
                    if(moonCounter == moon.length-1){
                        moonCounter = 0;
                    }
                    location.hash = f.join('');
                    await sleep(50);
                }
            }
        }
        loop();
    </script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>